# Generated by Django 3.2.5 on 2022-01-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribers',
            old_name='su_email',
            new_name='Sub_email',
        ),
    ]
