# Generated by Django 3.2.5 on 2022-01-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_su_email_subscribers_sub_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='Sub_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
