# Generated by Django 3.2.5 on 2022-01-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_subscribers_sub_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='massege',
        ),
        migrations.AddField(
            model_name='contact',
            name='e_message',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='Sub_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
