# Generated by Django 3.2.5 on 2022-01-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20220108_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='e_message',
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
