# Generated by Django 3.2.5 on 2022-01-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20220108_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='FROM',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
