# Generated by Django 3.2.5 on 2022-01-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_contact_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='FROM',
        ),
    ]
